baseurl = ""
languageCode = "en-us"
title = "Balkian's site" 
theme = "balkian"
preserveTaxonomyNames = true
disqusShortname = "balkian"
googleAnalytics = ""
Paginate = 5
pygmentsCodeFences = true
pygmentsOptions = "linenos=table"
summaryLength = 50
relativeURLs = true
copyright = "This work is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License."

[outputs]
  home = ["HTML", "RSS", "JSON"]

[taxonomies]
  category = "categories"
  tag = "tags"
  post = "posts"

[Author]
    name = "J. Fernando Sánchez"
    profile = "http://balkian.com"

[params]
    # Sets the meta tag description, usually reserved for the main page
    description          = "Balkian's ramblings"
    # This will appear on the top left of the navigation bar
    navbarTitle          = "Balkian"
    # Social media buttons that appear on the sidebar
    socialAppearAtTop    = true
    socialAppearAtBottom = true
    # set this to the section name if section is not post
    viewMorePostLink     = "/post/"

    subtitle = "Build a beautiful and simple website in minutes"
    logo = "img/me.png"
    favicon = "img/favicon.ico"
    dateFormat = "January 2, 2006"
    commit = false
    rss = true
    comments = true

# Optional Params
    categoriesByCount    = true
    includeReadingTime   = true
    # The set of favicons used are based on the write-up from this link:
    # https://github.com/audreyr/favicon-cheat-sheet
    # Please see the favicon partial template for more information
    loadFavicon          = false
    faviconVersion       = ""

    # Load custom CSS or JavaScript files. This replaces the deprecated params
    # minifiedFilesCSS and minifiedFilesJS. The variable is an array so that you
    # can load multiple files if necessary. You can also load the standard theme
    # files by adding the value, "default".
    # customCSS            = ["default", "/path/to/file"]
    # customJS             = ["default", "/path/to/file"]

    # Loading min files for exampleSite
    customCSS            = ["/css/main.min.css"]
    customJS             = ["/js/main.min.js"]

# parms.intro will appear on the sidebar
# This is optional, but it's suggested to use
[params.intro]
    header    = "Balkian"


    paragraph = "J. Fernando Sánchez"

    about     = "Fernando Sánchez's blog"

# This will also appear on the sidebar.
# A width of less than 100px is recommended
# This is optional
[params.intro.pic]
    src       = "/img/logo.png"
    # modify your picture in the shape of a circle or
    # future imperfect's hexagonal shape
    circle    = true
    imperfect = false
    width     = "300px"
    alt       = "Balkian"

# Adjust the amount of recent posts on the sidebar.
# This is optional. The default value 5 will be used
[params.postAmount]
    sidebar = 4

# # Set up your menu items in the navigation bar
# # You can use identifier to prepend a font awesome icon to your text
# [[menu.main]]
#     name = "Blog"
#     url = "/post"
#     identifier = "fa fa-newspaper-o"
#     weight = 1

[[menu.main]]
    name = "Blog"
    url = "/post/"
    identifier = "post"
    weight = 1

[[menu.main]]
    name = "Tags"
    url = "/tags/"
    identifier = "tags"
    weight = 2

[[menu.main]]
    name = "Cheatsheets"
    identifier = "cheatsheet"
    url = "/cheatsheet/"
    weight = 3

[[menu.main]]
    name = "Projects"
    identifier = "project"
    url = "/project/"


# Insert your username and the icon will apear on the page as long as
# socialAppearAtTop or socialAppearAtBottom is set to true in the params area
# The social media icons will appear on the sidebar
[social]
    github          = "balkian"
    bitbucket       = "balkian"
    jsfiddle        = ""
    codepen         = ""
    foursquare      = ""
    dribbble        = ""
    deviantart      = ""
    behance         = ""
    flickr          = ""
    instagram       = ""
    youtube         = ""
    vimeo           = ""
    vine            = ""
    medium          = ""
    wordpress       = ""
    tumblr          = ""
    xing            = ""
    linkedin        = ""
    slideshare      = ""
    stackoverflow   = "balkian"
    reddit          = "balkian"
    pinterest       = ""
    googleplus      = ""
    facebook        = ""
    facebook_admin  = ""
    twitter_domain  = ""
    twitter         = "balkian"
    email           = ""

[markup]
  [markup.tableOfContents]
    endLevel = 3
    startLevel = 1

[markup.goldmark.renderer]
unsafe= true