# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Balkian"
license = "MIT"
licenselink = "https://github.com/balkian/balkian-hugo-theme/blob/master/LICENSE.md"
description = "A very simple self-made theme"
homepage = "https://github.com/balkian/balkian-hugo-theme/"
tags = ["", ""]
features = ["", ""]
min_version = 0.18

[author]
  name = "J. Fernando Sánchez"
  homepage = "http://balkian.com"
